praw:
  username: ""
  password: ""
  client_id: ""
  client_secret: ""
  user_agent: ""

twitch:
  gql:
    OAuth:
    ClientId: kimne78kx3ncx6brgo4mv6wki5h1ko
subreddits:
  - livestreamfail
  - rpclipsgta
  - clipsync