praw: # https://praw.readthedocs.io/en/stable/getting_started/quick_start.html#authorized-reddit-instances
  username: ""
  password: ""
  client_id: ""
  client_secret: ""
  user_agent: ""

twitch:
  gql:
    OAuth: # client facing OAuth token for your twitch account
    ClientId: kimne78kx3ncx6brgo4mv6wki5h1ko # this is twitch's own client-id

subreddits:
  - livestreamfail
  - rpclipsgta
  - clipsync